Repository DatHoang192/insomnia, pull requests merged in 2024-01, with the labels that each got.

#9 Feature/dev 008 setter
  .vscode/settings.json
  packages/insomnia/src/common/constants.ts
  packages/insomnia/src/common/render.ts
  packages/insomnia/src/models/index.ts
  packages/insomnia/src/models/request-setter.ts
  packages/insomnia/src/network/network.ts
  packages/insomnia/src/plugins/context/network.ts
  packages/insomnia/src/ui/components/editors/utils/request-event-setter-editor.tsx
  packages/insomnia/src/ui/components/editors/utils/setter-event-row-editor.tsx
  packages/insomnia/src/ui/components/key-value-editor/editor.tsx
  packages/insomnia/src/ui/components/key-value-editor/row.tsx
  packages/insomnia/src/ui/components/variable-setter-editor/row.tsx
  packages/insomnia/src/ui/routes/request.tsx
Labels: enhancement

#14 DEV021 setter after request fix
  packages/insomnia/src/plugins/context/network.ts
  packages/insomnia/src/ui/components/editors/utils/setter-event-row-editor.tsx
  packages/insomnia/src/ui/routes/request.tsx
Labels: bug

#15 DEV013 setter multiline
  packages/insomnia/src/ui/components/variable-setter-editor/row.tsx
Labels: bug

#16 DEV021 disabled checkbox
  packages/insomnia/src/ui/components/editors/utils/request-utils-editors.tsx
  packages/insomnia/src/ui/components/editors/utils/setter-event-row-editor.tsx
  packages/insomnia/src/ui/components/variable-setter-editor/row.tsx
Labels: bug

#17 DEV017 disable chevron when there is no setters
  packages/insomnia/src/ui/components/editors/utils/setter-event-row-editor.tsx
Labels: bug, enhancement

#18 Feature/dev016 data set client code
  packages/insomnia/src/common/har.ts
  packages/insomnia/src/ui/components/editors/utils/dataset-row-editor.tsx
  packages/insomnia/src/ui/components/modals/generate-code-modal.tsx
Labels: bug, enhancement

#20 Bugfix/dev085 util tab setting refactor
  packages/insomnia/src/ui/components/editors/utils/request-settings-editor.tsx
  packages/insomnia/src/ui/components/modals/request-settings-modal.tsx
Labels: enhancement

#25 DEV089 collapse all folders button
  packages/insomnia/src/ui/routes/debug.tsx
Labels: bug

#26 DEV094 ENV modal
  packages/insomnia/src/ui/components/templating/filter-row-editor.tsx
  packages/insomnia/src/ui/components/templating/plugin-filter-args-editor.tsx
  packages/insomnia/src/ui/components/templating/variable-editor.tsx
Labels: enhancement

#27 DEV091 make editor search bar longer
  packages/insomnia/src/ui/css/main.css
Labels: bug
